version: '3.8'

services:
  asterisk:
    image: roman220/asterisk-certified:18.9-cert8-rc1
    hostname: asterisk
    container_name: asterisk-container
#    command: tail -f /dev/null
    network_mode: host
    restart: unless-stopped
#    ports:
#      - "5060:5060/udp"
#      - "5060:5060/tcp"
    volumes:
      - ./runtime/asterisk/logs:/var/log/asterisk
      - ./runtime/asterisk/etc:/etc/asterisk
    depends_on:
      - mariadb
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

  mariadb:
    image: mariadb
    hostname: mariadb
    container_name: mariadb-container
    network_mode: host
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
#      MYSQL_DATABASE: asteriskcdrdb
#    ports:
#      - "3306:3306"
    volumes:
      - ./runtime/mariadb/data:/var/lib/mysql
      - ./runtime/html-config/cdr.sql:/docker-entrypoint-initdb.d/init.sql

  php-fpm:
    image: roman220/php-fpm
    hostname: nginx
    container_name: php-fpm-container
#    command: tail -f /dev/null
    network_mode: host
    restart: unless-stopped
#    ports:
#      - "8080:80/tcp"
#      - "8443:443/tcp"
    volumes:
      - ./runtime/html:/var/www/html

  rtpengine:
    build: rtpengine/
    container_name: rtpengine-container
    network_mode: host
    restart: unless-stopped

  kamailio:
    build: kamailio/
    command: tail -f /dev/null
    container_name: kamailio-container
    network_mode: host
    restart: unless-stopped

